# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0da1649c5c78de028e48e6ffe400d47222d7d58bd911f46475727bb523a328e3976b6fd09751159cd96989b9a66da09c4557d670663e2dfce8385338aa6313f
  # sandbox
  # silverfin:
  #   id: k029Ga0jlE4RLI_qjnNElVMHX1a33G-06NUwldwOqQ8
  #   secret: MxVjSjwHVh3Eaa3eHbaEkqtGsBos6QjNMxgovOFIxdA
  #   url: https://sandbox.getsilverfin.com
  #   redirect_url: https://localhost/oauth/silverfin
  # local
  silverfin:
    id: pawjbFB915SPkyZyUOCnL61nc3GIDqItw3ugNF2zcrc
    secret: n_dPvLu1Wr1oidnvAL0jc0ifEfHZbzsQnxi5T4wbTdY
    url: https://live.getsilverfin.com
    redirect_url: https://localhost:3000/oauth/silverfin
  companies_house:
    presenter_id: "66664035000"
    presenter_authentication_code: FCL79Z2V2Q2
    package_reference: "0012"
    test_flag: "1"
    market_place_export_file_ids:
      - 203944570
  hmrc:
    id: BIrbyq1iNlBdOzvvPkN2e701pgca
    secret: cf2bce5e-c6a6-4be9-98b2-d0809a4c44bf
    url: "https://test-api.service.hmrc.gov.uk"
    redirect_url: "http://localhost:3001/hmrc_integration/oauth_callback"
  tax_be:
    market_place_export_file_ids:
      - 75873341

test:
  secret_key_base: f302817bac46d8d1b7f4d38f2882519e7da64708c13ba739b5cc48afcb01edc2b99a59770b796b19a0dc9f208f81ffcf4ebe61bbd96942f4299f12772f1acfbe
  silverfin:
    id: 7071e9294d37d62488b080571109b98cf8759e2b3b6b3d4ea34e411bacb48cf8
    secret: 1a8453085f7645e8ee5f09fe4c5b4f12d9d13809a145a58fb8ed2dd33fdbc10d
    url: http://localhost:3000
    redirect_url: http://localhost:3001/oauth/silverfin
  companies_house:
    presenter_id: "66664035000"
    presenter_authentication_code: FCL79Z2V2Q2
    package_reference: "0012"
    test_flag: "1"
  hmrc:
    id: BIrbyq1iNlBdOzvvPkN2e701pgca
    secret: cf2bce5e-c6a6-4be9-98b2-d0809a4c44bf
    url: "https://test-api.service.hmrc.gov.uk"
    redirect_url: "http://localhost:3001/hmrc_integration/oauth_callback"

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  silverfin:
    id: <%= ENV["SILVERFIN_ID"] %>
    secret: <%= ENV["SILVERFIN_SECRET"] %>
    url: https://live.getsilverfin.com
    redirect_url: https://fintrax-dashboard.herokuapp.com/oauth/silverfin
  companies_house:
    package_reference: "4022"
    test_flag: "0"
    presenter_id: "<%= ENV["COMPANIES_HOUSE_PRESENTER_ID"] %>"
    presenter_authentication_code: <%= ENV["COMPANIES_HOUSE_PRESENTER_AUTHENTICATION_CODE"] %>
    market_place_export_file_ids:
      - 9
      - 12
  hmrc:
    id: "<%= ENV["HMRC_ID"] %>"
    secret: "<%= ENV["HMRC_SECRET"] %>"
    url: "https://api.service.hmrc.gov.uk"
    redirect_url: "https://integrations.getsilverfin.com/hmrc_integration/oauth_callback"
  tax_be:
    market_place_export_file_ids:
      - 10
